[general]
separator = " "
default_icon = "ï"

[options]
no_names = true

[icons]
"kitty" = "ï„ "
"Emacs" = "ï…œ"
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
Thunderbird = "ïƒ "
thunderbird = "ïƒ "
Betterbird = "ïƒ "
betterbird = "ïƒ "
Zathura = "ï‡"
default_icon = "ğŸ’€"
feh = "ï€¾"
Pavucontrol = "ğŸ§"
Zotero = "Z"
pcmanfm = "ğŸ–¿"
Pcmanfm = "ğŸ–¿"
Spotify = "ï†¼"
spotify = "ï†¼"