version = "1.1.14"

[format]
# Deduplicate icons if enable.
# A superscripted counter will be added.
# dedup = false
# dedup_inactive_fullscreen = false # dedup more
# window delimiter
# delim = " "
# max_clients = 30 # you should not need this

# available formatter:
# {counter_sup} - superscripted count of clients on the workspace, and simple {counter}, {delim}
# {icon}, {client}
# workspace formatter
workspace = "[{name}]: {clients}" # {id}, {delim} and {clients} are supported
workspace_empty = "[{name}]" # {id}, {delim} and {clients} are supported
# client formatter
client = "{icon}"
client_active = "{icon}"

# deduplicate client formatter
# client_fullscreen = "[{icon}]"
# client_dup = "{client}{counter_sup}"
# client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused}"
# client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused}"

[class]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
DEFAULT = "ğŸ’€"
"(?i)Kitty" = "ï„ "

"Emacs" = "ï…œ"
"TelegramDesktop" = "ï‹†"
"[Ff]irefox" = "ï‰©"
"[Tt]hunderbird" = "ïƒ "
"Zathura" = "ï‡"
"feh" = "ï€¾"
"[Pp]avucontrol" = "ğŸ§"
"Zotero" = "Z"
"[Pp]cmanfm" = "ğŸ–¿"
"[Ss]potify" = "ï†¼"

[workspaces_name]
1 = "a"
2 = "s"
3 = "d"
4 = "f"
5 = "g"
6 = "y"
7 = "x"
8 = "c"
9 = "v"
10 = "m"